Repository josh-development/providers, pull requests merged in 2022-05, with the labels that each got.

#45 chore: add git attributes
  .gitattributes
  yarn.lock
Labels: Priority: High, Status: Review Ready, Type: Maintenance

#42 feat: update all providers
  .vscode/settings.json
  benchmarks/src/lib/Benchmark.ts
  benchmarks/src/lib/constants/benchmark-tests.ts
  benchmarks/src/lib/functions/createCard.ts
  package.json
  packages/json/package.json
  packages/json/src/lib/JSONProvider.ts
  packages/json/tests/lib/JSONProvider.test.ts
  packages/mongo/package.json
  packages/mongo/src/lib/MongoProvider.ts
  packages/mongo/tests/lib/MongoProvider.test.ts
  scripts/generate/jobs.mjs
  tests/runProviderTest.ts
  tests/tsconfig.json
  yarn.lock
Labels: Priority: High, SEM: Major, Status: Review Ready, Type: Maintenance, Type: Provider

#47 ci(codeql-analysis): add code scanning
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/continuous-tests.yml
  package.json
  scripts/generate/generate.mjs
  yarn.lock
Labels: Meta: Cleanup, Meta: GitHub, Priority: High, SEM: N/A, Status: Review Ready

#50 chore(benchmarks): fix
  benchmarks/src/lib/constants/benchmark-tests.ts
Labels: SEM: N/A, Status: Review Ready

#66 refactor/switch to non tag versions
  .husky/pre-commit
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarnrc.yml
  package.json
  packages/json/package.json
  packages/map/package.json
  packages/mongo/package.json
  packages/redis/package.json
  yarn.lock
Labels: Meta: Dependencies, Meta: Refactor, Priority: High, SEM: N/A, Status: Review Ready
